### ISSUE TITLE
fiji and cellprofiler pro and con

### ISSUE THREAD

**Issue by tischi** [tischi/imagej-courses#23]
@imagejan @ssgpers 

if you have some opinions here that would be also helpful:

https://github.com/tischi/imagej-courses/blob/master/lectures/cellprofiler-pro-con.md#cellprofiler
https://github.com/tischi/imagej-courses/blob/master/lectures/fiji-pro-con.md#the-pros-and-cons-of-fiji

**Comment by ssgpers** [comment]
I would not consider "One way to do things" to be pros for Cell Profiler. For starting users maybe, but algorithms may be not optimal. For a bit experienced user possibility to choose and compare is an advantage.

To avoid the need classifying things as either pros or cons, you can put another subtitle, e.g. "distinctive features" on both slides
